### ISSUE TITLE
Feature Request: Implement EPC-QR-Code Support on Invoices (European Payments Council)

### ISSUE THREAD

**Issue by sutiv** [onfuseag/swiss_accounting_software#1]
Hallo zusammen,

kann man dieses Paket auch für Deutschland nutzen? Oder welche Anpassung wäre dafür notwendig?
[Linked Issue](https://github.com/frappe/erpnext/issues/39919)

Grüße

**Comment by cdiethelm** [comment]
Hallo, 

Wie es aussieht sind da fast die selben Daten drin als im Regulären Swiss QR Code.  Könnte man also als Option wählen, wenn der Kunde aus Land = DE kommt.

Gibt es Beispielbilder für die Rechnung in DE? Siehe Beispiel CH.
![image](https://github.com/user-attachments/assets/43a57ed7-4704-448a-9a61-cb54f89346b4)

**Comment by sutiv** [comment]
Hallo,
ich habe schon häufig welche erhalten - die sehen so aus:
![image](https://github.com/user-attachments/assets/f11d5a30-0103-4a8b-b3a7-d5c1d2835a38)

Ich habe den Issue aber geschlossen, weil es mittlerweile aus der Deutschen Community heraus ein Projekt gibt, welches Geld für die Entwicklung gesammelt hat und das alles umsetzen will... [ERPNext-Forum](https://discuss.frappe.io/t/e-rechnungen-in-erpnext/123744/11)

**Comment by cdiethelm** [comment]
Vielen Dank für das Update. Interessantes Projekt 👍
