### ISSUE TITLE
syntax error in pain001.py

### ISSUE THREAD

**Issue by mozilla0** [onfuseag/swiss_accounting_software#2]
The app could not deploy on frappe cloud, because there is a syntax error in the initial commit of the pain001.py on code line 15 (payments= )

![2024-09-10_234043](https://github.com/user-attachments/assets/66b31b1a-055f-48ed-8a84-40860d4d110d)

**Comment by cdiethelm** [comment]
Hi, 

This should as of the latest release.

Let me know if that has fixed your issue.
[Fix](https://github.com/onfuseag/swiss_accounting_software/commit/394027f159c49e1c18329a3bce524fb538970742)

**Comment by mozilla0** [comment]
@cdiethelm the last update fix the issue - important note for all [Phamos Swiss Accounting](https://github.com/phamos-eu/Swiss-Accounting-Integration/tree/version-15) user --> remove first the old Phamos app and install then the one from Onefuse, otherwise it will not working (shared some module names)
